### PR TITLE
added random plugin

### PR DESCRIPTION
**Pull request by rleh**

### CODE REVIEW

**Comment by Turakar** [comment]
I would like to habe the other dices, too. Especially W20 and W3. Maybe it is helpful to habe an optional parameter for setting the max value.

**Comment by rleh** [comment]
"!random 1 20" and "!random 1 3" do what you want.
You can specify to upper and lower bound with "!random [lower upper]".

**Comment by Turakar** [comment]
It nicht be helpful to be able to only specify the upper bound and then default the lower to 1, AS in most cases  this will be used as an utilityband has to be easy and fast to use.

**Comment by Turakar** [comment]
And there is a typo in the help. You are saying "roll a six-sided die", but "dice" is want you mean.

**Comment by rleh** [comment]
Now the lower bound parameter is optional, if only one parameter is supplied 1 is the lower bound.

**Comment by rleh** [comment]
die is singular, dice is plural, but more common ;-)  (http://grammarist.com/usage/dice-die/)

**Pull request merged**
